# Generated by Django 4.2.6 on 2023-10-20 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'allergies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('idappointment', models.AutoField(db_column='idAppointment', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('First Visit', 'First Visit'), ('Follow up', 'Follow up'), ('Check Up', 'Check Up'), ('Consultation', 'Consultation'), ('Surgery', 'Surgery'), ('Post Surgery', 'Post Surgery')], max_length=20, null=True)),
                ('nature', models.CharField(blank=True, choices=[('Clinic', 'Clinic'), ('Virtual', 'Virtual')], max_length=10, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('chief', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('idattachment', models.AutoField(db_column='idAttachment', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('files', models.BinaryField(blank=True, null=True)),
                ('attachment_file', models.FileField(upload_to='attachments/')),
            ],
            options={
                'db_table': 'attachment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'billing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_clinic', max_length=20, null=True)),
                ('location', models.TextField(blank=True, db_column='location_clinic', null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'clinic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('iddiagnosis', models.AutoField(db_column='idDiagnosis', primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
            ],
            options={
                'db_table': 'myapp_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('idinsurance', models.AutoField(db_column='idInsurance', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=20, null=True)),
                ('insurance_company', models.CharField(blank=True, db_column='Insurance_company', max_length=30, null=True)),
            ],
            options={
                'db_table': 'insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('idmedical_test', models.AutoField(db_column='idMedical_test', primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=45, null=True)),
                ('test_code', models.CharField(blank=True, max_length=10, null=True)),
                ('normal_average', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('minimum', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'medical_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('idnotes', models.AutoField(db_column='idNotes', primary_key=True, serialize=False)),
                ('saved_notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ssn', models.CharField(blank=True, db_column='SSN', max_length=20, null=True)),
                ('mrn', models.CharField(blank=True, db_column='MRN', max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, db_column='Blood_type', max_length=5, null=True)),
                ('first_name', models.CharField(blank=True, db_column='First_name', max_length=10, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_name', max_length=15, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], db_column='Gender', max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('first_name_emergency', models.CharField(blank=True, db_column='First_name_emergency', max_length=10, null=True)),
                ('last_name_emergency', models.CharField(blank=True, db_column='Last_name_emergency', max_length=15, null=True)),
                ('phone_emergency', models.CharField(blank=True, max_length=30, null=True)),
                ('relation_emergency', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHasDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'patient_has_diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHasInsurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'patient_has_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHasPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dose', models.CharField(blank=True, db_column='Dose', max_length=45, null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=30, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=45, null=True)),
                ('strength', models.CharField(blank=True, db_column='Strength', max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_has_prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHasProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'patient_has_problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHasReferralDoctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_has_referral_doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHasSurgery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'patient_has_surgery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientHasVital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'patient_has_vital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientReceiveTemplates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=1, null=True)),
            ],
            options={
                'db_table': 'patient_receive_templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('idprescription', models.AutoField(db_column='idPrescription', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('instruction', models.TextField(blank=True, db_column='Instruction', null=True)),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(db_column='ICD', primary_key=True, serialize=False)),
                ('icd', models.CharField(blank=True, db_column='ICD_number', max_length=15, null=True)),
                ('problem_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadiologyResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('result_text', models.TextField(blank=True, db_column='Result_Text', null=True)),
                ('conclusion', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('rad_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'radiology_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadiologyTest',
            fields=[
                ('idradiology_test', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('test_code', models.CharField(blank=True, max_length=10, null=True)),
                ('imaging_type', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'radiology_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralDoctors',
            fields=[
                ('idreferral_doctors', models.AutoField(db_column='idReferral_Doctors', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='First_name', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_name', max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='Middle_name', max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('speciality', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_speciality', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'referral_doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('value', models.DecimalField(blank=True, db_column='Value', decimal_places=5, max_digits=10, null=True)),
                ('value_type', models.CharField(blank=True, db_column='vaue_type', max_length=20, null=True)),
                ('receive_type', models.CharField(blank=True, max_length=10, null=True)),
                ('lab_date', models.DateField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idrole', models.AutoField(db_column='idRole', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id_social', models.AutoField(db_column='ID_Social', primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'social_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'social_media_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialNeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'special_need',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('idsurgery', models.AutoField(db_column='idSurgery', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
            ],
            options={
                'db_table': 'surgery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('idtasks', models.AutoField(db_column='idTasks', primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('task_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('idtemplates', models.AutoField(db_column='idTemplates', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='First_name', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_name', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersHasPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'users_has_patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersHasReferralDoctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'users_has_referral_doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersHasTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'users_has_tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersHasTemplates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'users_has_templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualMeet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.TextField(blank=True, db_column='url_virtual', null=True)),
            ],
            options={
                'db_table': 'virtual_meet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('idvital', models.AutoField(db_column='idVital', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'vital',
                'managed': False,
            },
        ),
    ]
