# Generated by Django 4.2.5 on 2023-11-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentReminder',
            fields=[
                ('idAttachment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('files', models.BinaryField(null=True)),
                ('attachment_file', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': ' attachmentreminder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('idrecurrence', models.AutoField(primary_key=True, serialize=False)),
                ('send', models.CharField(max_length=20, null=True)),
                ('appointment', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('occurrence', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'recurrence',
                'managed': False,
            },
        ),
    ]
