# Generated by Django 4.2.5 on 2023-11-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_generalhealthreminders_patienteducation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachmentreminder',
            table='attachmentreminder',
        ),
    ]
