# Generated by Django 4.2.5 on 2023-11-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_message_room'),
        ('myapp', '0004_alter_attachmentreminder_table'),
    ]

    operations = [
    ]
